# Generated by Django 5.0.6 on 2024-06-09 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colegios',
            name='nombre',
            field=models.CharField(max_length=100, null=True, verbose_name='Nombre del colegio'),
        ),
    ]
