# Generated by Django 5.0.6 on 2024-05-18 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='fecha',
            field=models.DateTimeField(),
        ),
    ]
