# Generated by Django 5.0.6 on 2024-05-18 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencias', '0003_alter_asistencia_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='hora',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='fecha',
            field=models.DateField(null=True),
        ),
    ]
